version: '3.6'
services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8443:8443'
      - '50000:50000'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /mnt/video:/video
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always
